### ISSUE TITLE
Pauly's face becomes distorted

### ISSUE THREAD

**Issue by amroco** [angmelanie/paulyplots#2]
Is there a way to scale Pauly's face, without pre-determining the graph dimensions?? I change the graph dimensions in the window by stretching the margins and his face goes weird!
Pleaaaaaaseee!!! I really really need this! I have a really important paper I have to write and it simply won't be the same without a paulyplot!

Thanks for coming to the rescue!

**Comment by amroco** [comment]
I've decided I kind of like it this way.

**Comment by angmelanie** [comment]
Hi @amroco - as you are someone who works closely with pauly, thought you would be the best candidate to assess the dimension of his face and fix this issue. I trust your judgement if you say you like it as it is now. Please stay tune for version 2.0.0.2.1.1.3.4.b which will feature a variety of pauly faces to select from.

**Comment by amroco** [comment]
Thank you @angmelanie -
As someone who also works closely with Pauly, I appreciate your acknowledgement of my senior candidacy on the delicate subject of distorting empolyers' faces while developing functional and aesthetic plotting packages using their images. I look forward to further distorted or non-distorted images in the future.
